// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wyvobG6MUIcgxqGXVOlTaIJIliyTGEA',
    appId: '1:463573837548:web:2fac71feec8be5efbf27c9',
    messagingSenderId: '463573837548',
    projectId: 'tasktracker-96e5a',
    authDomain: 'tasktracker-96e5a.firebaseapp.com',
    storageBucket: 'tasktracker-96e5a.firebasestorage.app',
    measurementId: 'G-1JBFK6ZWCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg42udvCDXjwXZkBDzWZ7MnyzZTNivy-E',
    appId: '1:463573837548:android:808d98789e728b57bf27c9',
    messagingSenderId: '463573837548',
    projectId: 'tasktracker-96e5a',
    storageBucket: 'tasktracker-96e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUrIil10tXFKLw5Ju5JTvb0Bt161L1O2c',
    appId: '1:463573837548:ios:d3afb3b1c705d12bbf27c9',
    messagingSenderId: '463573837548',
    projectId: 'tasktracker-96e5a',
    storageBucket: 'tasktracker-96e5a.firebasestorage.app',
    iosBundleId: 'com.moodjournal.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUrIil10tXFKLw5Ju5JTvb0Bt161L1O2c',
    appId: '1:463573837548:ios:f40f0f705c10b496bf27c9',
    messagingSenderId: '463573837548',
    projectId: 'tasktracker-96e5a',
    storageBucket: 'tasktracker-96e5a.firebasestorage.app',
    iosBundleId: 'com.example.homeassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3wyvobG6MUIcgxqGXVOlTaIJIliyTGEA',
    appId: '1:463573837548:web:7ae659b98b0da736bf27c9',
    messagingSenderId: '463573837548',
    projectId: 'tasktracker-96e5a',
    authDomain: 'tasktracker-96e5a.firebaseapp.com',
    storageBucket: 'tasktracker-96e5a.firebasestorage.app',
    measurementId: 'G-7SED3R4N7R',
  );
}
